### ISSUE TITLE
Estaría bien poder configurar un coste fijo

### ISSUE THREAD

**Issue by jjaammhh** [yinyang17/pvpc_energy#16]
Estaría bien poder configurar un coste fijo, de cara a que las facturas muestren el valor correcto, y que el panel de control de energía de HA pueda recoger los costes reales con facilidad

**Comment by neoalarrode** [comment]
No está contemplado en el complemente dado que está pensado para tarifas PVPC, pero puedes generar un sensor de coste manualmente con tu precio kWh y añadirlo en el Dashboard de energía

**Comment by yinyang17** [comment]
Hola,
para configurar un precio fijo en el panel de energía selecciona "Usar un precio estático" cuando añades el consumo.

<img width="426" alt="image" src="https://github.com/user-attachments/assets/56c4cbe7-ea5e-4bf1-aaf7-08c0e265386a">

Para las facturas no es posible indicar un precio fijo porque el importe se calcula con la página https://comparador.cnmc.gob.es/facturaluz/inicio/ y esta solo vale para tarifas pvpc.
Si tienes un precio fijo el cálculo de la factura lo hace tú comercializadora en base el contrato que tengas. Para lo que te pueden valer el importe de las facturas es para ver si con la tarifa pvpc pagarías menos que con la actual o viceversa y te conviene cambiar.

Un saludo.

**Comment by yinyang17** [comment]
Buenas,
ya me había fijado que las dos últimas opciones no funcionaban, pero creía que seleccionando primero el coste fijo y después indicando el consumo funcionaba pero por lo que veo no.

Revisando he visto que las 2 últimas opciones no se pueden utilizar con estas estadísticas porque no se crean a partir de un sensor, https://community.home-assistant.io/t/electricity-price-cannot-be-set-when-using-an-external-statistic/610886.

Podría añadir otra estadística con un precio fijo, pero no se si tiene sentido porque las facturas seguirían calculándose con el pvpc, así que solo valdría para el panel de energía y puede ser confuso.
Le doy una vuelta a ver si hay algún modo de hacerlo.

Un saludo.
