### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by sergey08** [yinyang17/pvpc_energy#2]
Buenas,

Al meter mis credenciales obtengo este mensaje:

Unknown error occurred

La cuenta existe y esta probada desde la web

Gracias de antemano

**Comment by sergey08** [comment]
Me respondo a mi mismo.

Tenía la autentificación en 2 pasos. La he quitado

**Comment by yinyang17** [comment]
Ok, añado a la documentación y al login que hay que desactivar el inicio de sesión en dos pasos.
Supongo que al quitarlo te ha funcionado ya correctamente, ¿no?

**Comment by sergey08** [comment]
Hola,

Pues la integración se crea, la nombra como el CUP, pero despues de casi 20h no ha creado entidades, y por tanto no veo ningún dato.

Gracias por tu trabajo

**Comment by yinyang17** [comment]
La integración no crea ninguna entidad. Crea 2 estadísticas que puedes añadir en el panel de energía, y un estado que lo puedes usar para ver en lovelace las últimas facturas (en la documentación está explicado).

Tengo que revisar porque creo que algo ha cambiado en UFD y no se descarga el día completo y puede que el último día de las estadísticas aparezca con consumos negativos (esta semana actualizaré la integración), pero no debería afectar a que tuvieses el histórico y deberías verlo en solo unos minutos, no 20 horas.

Un saludo.

**Comment by yinyang17** [comment]
Hola,
he subido una nueva versión que corrige un error en la descarga inicial de los consumos, con lo que ahora tendrías que ver las estadísticas y estado en 5-10 minutos.
No se obtienen los datos de las facturas porque ahora mismo no está funcionando la web de la cnmc (https://comparador.cnmc.gob.es/facturaluz/inicio/)
Un saludo.
