### ISSUE TITLE
Sin dispositivos ni entidades

### ISSUE THREAD

**Issue by Nachovilaboa** [yinyang17/pvpc_energy#3]
Al poner las credenciales me da de alta la integración pero no aparecen ni dispositivos, ni entidades

**Comment by yinyang17** [comment]
Hola, tras indicar las credenciales y el número de facturas si todo está ok deberías ver el CUPS y debajo si muestra sin dispositivos ni entidades.
![image](https://github.com/yinyang17/pvpc_energy/assets/87585691/199dd964-d76b-415e-9c98-26c7f6fc9d69)
Lo que crea la integración son 2 estadísticas y un estado (tardará unos minutos en aparecer ya que descarga el histórico de consumo y precios que exista en UFD).
En la documentación indico como utilizar las estadísticas y el estado.

**Comment by yinyang17** [comment]
Hola,
he subido una nueva versión que corrige un error en la descarga inicial de los consumos, con lo que ahora tendrías que ver las estadísticas y estado en 5-10 minutos.
No se obtienen los datos de las facturas porque ahora mismo no está funcionando la web de la cnmc (https://comparador.cnmc.gob.es/facturaluz/inicio/)
Un saludo.
