### ISSUE TITLE
Fallos en la última update

### ISSUE THREAD

**Issue by javiges** [yinyang17/pvpc_energy#6]
Desde la segunda actualización de hoy me sale este error y ya no me muestra los datos de factura:
2024-01-29 15:54:28.967 ERROR (MainThread) [custom_components.pvpc_energy.ufd] status_code: 429, response: Too Many Requests

Este es el fallo por si puede arreglarlo, gracias por tú trabajo.

**Comment by yinyang17** [comment]
Hola,
este mensaje no es un error (me apunto para que no aparezca así), sino que no se pueden descargar todos los datos de consumo seguidos ya que hay un límite en el número de peticiones.
Con cada ejecución diaria se irá descargando los consumos pasados hasta el máximo disponible.

A pesar de esto si deberías poder ver alguna factura (más si ya las veías antes). Necesitaría tener más logs para ver cual puede ser el problema. Si quieres añade a configuration.yaml esta configuración para ver todos los logs y copialos por aquí desde "DEBUG (MainThread) [custom_components.pvpc_energy.coordinator] START - import_energy_data()" (revisa y elimina si hay datos personales (usuario, password) en los logs)
```
logger:
  logs:
    custom_components.pvpc_energy: debug
```

**Comment by javiges** [comment]
Quité la instalación del tu integración por que llevaba de días sin darme datos, lo puse y no arranca ha, me daba esto
2024-02-10 16:51:28.322 ERROR (MainThread) [custom_components.pvpc_energy.ufd] status_code: 429, response: Too Many Requests
2024-02-10 16:51:30.015 ERROR (MainThread) [custom_components.pvpc_energy.ufd] status_code: 429, response: Too Many Requests
2024-02-10 16:51:30.268 ERROR (MainThread) [custom_components.pvpc_energy.ufd] status_code: 429, response: Too Many Requests
2024-02-10 16:51:30.333 ERROR (MainThread) [custom_components.pvpc_energy.ufd] status_code: 429, response: Too Many Requests
Tuve que sacar de copia de seguridad , ya que estaba integrado todo eliminé la integración del cups y volví a darle y lo cogió, pero cuando voy al panel no aparece el pvpc,.
Sñe que es un trabajo arduo y te estarán dando el coñazo , seguramente será por culpa de ha, gracias por el aporte

**Comment by yinyang17** [comment]
Hola, el problema es que la web de UFD ha puesto algún tipo de control que limita el número de peticiones que se pueden hacer, por lo que en lugar de descargar todo el histórico de consumo tras instalar solo se puede descargar unas semanas.
La integración debería ir descargando cada día un poco más de histórico si la dejas configurada (se ejecuta cada día a las 7:05).
Estoy viendo la opción de descargar los datos de consumo de Datadis en lugar de UFD, que ahí no hay este problema.

Prueba a dejar la integración configurada para ver si al día siguiente ya tienes las estadísticas.

En cuanto a que no aparezcan datos nuevos cada día a veces el problema es que no están en UFD (a veces pasan 2 o 3 días sin actualizarlos). Si no aparecen en el panel de energía puedes probar a acceder a UFD. Si ahí tampoco están el problema no es la integración.

**Comment by javiges** [comment]
no me aparece le pvpc consumo, ni el pcpc coste en el panel de energia para ponerlos, solo los datos que tengo son del shelly em

**Comment by yinyang17** [comment]
Hola,
acabo de publicar la v.0.1.10 que soluciona el error "Too Many Requests" al obtener los consumos.
Lo he probado varias veces haciendo una instalación limpia y me ha descargado todo el histórico de datos de consumo (desde 02/2022).
Un saludo.

**Comment by yinyang17** [comment]
Hola,
he publicado la v0.1.11 ya que la anterior tenía un error que podía producir un bucle.
Si tienes algún problema con versiones anteriores haz una instalación de cero de esta versión y ya no debería dar problemas.
