### ISSUE TITLE
Error inicio session

### ISSUE THREAD

**Issue by Borja89** [yinyang17/pvpc_energy#7]
Buenas.
Lo primero gran trabajo. 
Tengo un problema a la hora de hacer el login, da error.
Tengo autoconsumo.

Indico las ultimas lineas del log:

File "/config/custom_components/pvpc_energy/config_flow.py", line 28, in async_step_user
await UFD.supplypoints()
File "/config/custom_components/pvpc_energy/ufd.py", line 164, in supplypoints
UFD.power_high = float(response['supplyPoints']['items'][0]['power1'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''

Gracias de antemano

**Comment by yinyang17** [comment]
Hola,
el problema parece al recuperar la potencia punta. ¿Puede que no tengas tarifa 2.0TD (con potencias diferentes para punta y valle)?
Esto es lo que veo yo en ufd.es:
<img width="371" alt="image" src="https://github.com/yinyang17/pvpc_energy/assets/87585691/c79517b9-0b6d-44e9-96c9-276063521d96">

**Comment by Borja89** [comment]
En mi caso no, adjunto lo mio.
¿Sabes como podria arreglarlo?

![Screenshot_20240217_142707_UFD](https://github.com/yinyang17/pvpc_energy/assets/11474599/70dace45-bc6e-4f65-9581-7ebec9c51c8e)

**Comment by yinyang17** [comment]
Hola, necesitaría saber que te devuelve UFD en la potencia, que no te llega igual que a mi.
Haz lo siguiente si puedes:
Añade los logs de la integración en el fichero "configuration.yaml"
```yaml
logger:
  logs:	
    custom_components.pvpc_energy: debug
```
Reinicia HomeAssistant y vuelve a intentar configurar la integración y revisa los logs. Antes del error que me has pasado estará lo que devuelve UFD. Necesitaría saber que ves ahí en los campos power. Por ejemplo en mi caso es:
> 'power': '4.6', 'power1': '4.6', 'power2': '4.6', 'power3': '', 'power4': '', 'power5': '', 'power6': ''

Y con eso modifico la integración para adaptarla a como te llega a ti la información.

Un saludo.

**Comment by Borja89** [comment]
Buenas tardes.

Esto me aparece:

'tipoDeLectura': 'NO TELEMEDIDO/NO TELEGESTIONADO', 'isMigrated': '0', 'contractStartDate': '24/09/2001', 'address': {'isCapital': '', 'provinceCode': '', 'province': 'TOLEDO', 'townCode': '', 'town': '*******', 'zipCode': '*****', 'zone': 'CASTILLA LA MANCHA', 'area': '', 'street': '***', 'streetType': '', 'number': '****', 'duplicator': '', 'singularEntity': '', 'colectiveEntity': '', 'stair': 'CA', 'floor': 'SA', 'complement': '', 'door': ''}, 'power': '', 'power1': '', 'power2': '', 'power3': '', 'power4': '', 'power5': '', 'power6': '', 'rate': '2.0TD PEAJE ATR',

Por lo que veo no devuelve ningún power.

Un saludo.

**Comment by Borja89** [comment]
Cambiando el ufd.py 

                    UFD.cups = response['supplyPoints']['items'][1]['cups']
                    UFD.power_high = float(response['supplyPoints']['items'][1]['power1'])
                    UFD.power_low = float(response['supplyPoints']['items'][1]['power2'])
                    UFD.zip_code = response['supplyPoints']['items'][1]['address']['zipCode']

Ha funcionado.

**Comment by yinyang17** [comment]
Ok, era lo que estaba pensando, que te devolviese más de un suministro.

Acabo de publicar la v0.1.12 que descarta los puntos de suministro sin datos de potencia, con lo que ya te debería funcionar correctamente.
Como ya lo tienes configurado este cambio no te afecta, pero si puedes elimina y vuelve a configurar la integración (después de haber actualizado a la v0.1.12) para comprobar que te funciona.

Un saludo.

**Comment by Borja89** [comment]
Lo he desinstalado y vuelto a instalar y configurar y parece que OK, muchísimas gracias.
