### ISSUE TITLE
Seleccionar CUPS

### ISSUE THREAD

**Issue by 21494** [yinyang17/pvpc_energy#8]
Gracias por la aportación. 
Tengo 2 suministros en 1 contrato, y por defecto me pilla el primero. ¿Hay alguna opción de seleccionar cual de ellos usar?
Estaria bien poder elegirlo
Saludos

**Comment by yinyang17** [comment]
Hola,
acabo de publicar la v0.2.0 que al configurar muestra un listado con los CUPS para poder seleccionarlo.
¿Puedes comprobar que te descargue los datos del segundo?
Un saludo.
![image](https://github.com/yinyang17/pvpc_energy/assets/87585691/f8935f14-c7a2-4113-a298-47d0cf6b1633)

**Comment by 21494** [comment]
Comprobado! Va genial gracias!

Pero he visto que si faltan datos sale esto asi de raro...

![image](https://github.com/yinyang17/pvpc_energy/assets/44348886/21ad824c-3826-4e1a-8c41-97c91538395c)

Es que viendo en la web de UFD no tengo datos del 24 y 25 por lo que sea.. Pero en vez de salir a 0kwh en la grafica mete esa medida rara.

![image](https://github.com/yinyang17/pvpc_energy/assets/44348886/b45b13c9-9c2b-48e2-8021-86dd947cfcfa)

Igual lo mejor que cuando no descarga un dato ponga el consumo medio o guarde un 0 para que no quede así, no sé. Estoy intentando actualizarlo desde el CSV pero ya no me lo pilla

Saludos! 😊

**Comment by yinyang17** [comment]
Hola,
si hay algún día u hora sin consumo en la gráfica no mostraría nada, la captura que envías con consumo negativo no tendría que salir así obviamente.
He reproducido más o menos el error y estoy viendo como solucionarlo y darle una vuelta a como indicar los días que no hay consumo. El problema de poner 0 en el consumo es que si UFD no devuelve datos de algún día por algún error puntual se quedaría el 0 y no lo actualizaría en días posteriores.
Le doy una vuelta para ver como identificar los días reales sin consumo y que no afecten a la gráfica.

Un saludo.

**Comment by 21494** [comment]
Pues no se por qué ocurre eso al transferirlo al HA.

¿Es posible actualizar los datos que ya se han introducido? Aunque se reemplacen con cada nueva descarga, se podría asignar un valor provisional y, si más adelante los datos correctos están disponibles, permitir que estos los actualicen. Supongo que es lo que ocurre con las lecturas estimadas y las reales.

He logrado corregir la gráfica manualmente. En la sección de estadísticas, el sistema identifica los valores outlayers y me permite editarlos. Quizás automatizar este proceso podría ser otra alternativa viable.

¡Gracias! 😀
Saludos

**Comment by yinyang17** [comment]
Hola,
acabo de publicar la versión v.0.2.1 que debería corregir el error en las estadísticas, ya que cuando no hay lecturas añade valores en la estadística para que se vea con consumo 0.
Para reprocesar las estadísticas y facturas en función de los datos de energía (fichero energy_data.csv) hay 2 servicios que puedes utilizar:
+ reprocess_energy_data: Regenera las estadísticas y facturas a partir de los datos del fichero.
+ force_import_energy_data: Descarga los datos de energía de los últimos 2 años y los sobreescribe en el fichero. Después regenera las estadísticas y facturas como el servicio anterior.

La sobreescritura de los datos de consumo no debería hacer falta, pero haciendo pruebas he visto que me da algún valor diferente al que ya tenía descargado, es decir, que UFD cambió ese dato en algún momento.

Yo te diría que uses el servicio force_import_energy_data para refrescar los datos por si por lo que sea alguno no es correcto. Le lleva unos minutos descargar y regenerar las estadísticas. Una vez hecho esto ya no deberías ver el valor negativo de consumo.
En caso de que te siga saliendo dime el periodo que tienes sin valores y así intento reproducirlo.

Un saludo.

**Comment by 21494** [comment]
Buenas!
Instalé la actualizacion pero como te comenté, ya lo habia editado en el csv con un valor estimado fijo.
Estaré mirando a ver actualizan el consumo de esos dias concretos y se sobreescriben los datos que puse manual. 

gracias, 

Saludos.
