### ISSUE TITLE
HomeAssistant no arranca

### ISSUE THREAD

**Issue by neoalarrode** [yinyang17/pvpc_energy#9]
Buenas!
Lo primero agradecerte tu fantástico trabajo, pero tras un mes utilizando el complemento me encuentro en una situación rara, cada vez que lo instalo, si la maquina donde está HomeAssistant instalado se reinicia, supervisor no vuelve a levantar.
A fin de encontrar cual era la causa del problema he generado una VM limpia y he ido instalando uno por uno y reiniciando todos los complementos que utilizo, (Tuya, TPlink Tapo, Meros, Adaptative lights, MQTT, GoveeMQTT y este) y parece que cuando se instala y se configura al reiniciar todo el SO de HomeAssistant devuelve este error, he tratado de repararlo con los siguientes 
<img width="1066" alt="Captura de pantalla 2024-03-12 a las 22 24 57" src="https://github.com/yinyang17/pvpc_energy/assets/46907653/1c5db563-9c5a-43b6-a187-15258dbbd813">
comandos
ha core rebuild
ha supervisor repair
pero ninguno de ellos funciona.
¿Sabes a que puede deberse esta incidencia?
He dejado una snapshot del SO con el complemento instalado y configurado por si necesitas mas información al respecto.
Gracias y un saludo

**Comment by yinyang17** [comment]
Hola,
ni idea de a que puede deberse, nunca me había pasado y hace bastantes meses que estoy con la integración.
Supongo que el problema puede venir de algo relacionado con tus consumos. Haz lo siguiente para ver si veo de donde puede venir el problema:
- Supongo que si solo añades la integración pero no la configuras no tienes ningún problema y home assistant se inicia corrrectamente, ¿no?
- Activa en "configuration.yml" el nivel debug de los logs. Cuando configuras la integración aparecerán muchos logs hasta que acabe de descargar los consumos y precios y debería acabar con "[custom_components.pvpc_energy.coordinator] END - import_energy_data". Pásame los últimos logs a ver si veo algo y mira también si en el directorio user_files de la integración tienes uno o dos ficheros con los consumos y facturas.
```yaml
logger:
  logs:
    custom_components.pvpc_energy: debug
```

**Comment by neoalarrode** [comment]
Buenas!
Disculpa la tardanza en contestarte, estuve sin internet por un problema técnico.
Te comento, intenté anoche lo que me dijiste pero UFD está completamente tumbado a si que lo acabo de volver a intentar en la VM clon y parece que ya funciona todo bien, lo he instalado configurado y reiniciado y ha arrancado sin problema, estoy ahora haciéndolo en la original a ver si obtengo el mismo resultado y te confirmo

**Comment by neoalarrode** [comment]
Confirmado, parece que todo venía por algún error de UFD, ya funciona perfecto y diría que ha recogido los datos más rápido, antes tardaba un par de minutos hasta que aparecía la entidad en el panel de energía y ahora con un par de segundos ha sido más que suficiente!
